GROUP_ID=io.github.ackeecz
POM_URL=https://github.com/AckeeCZ/danger-kotlin-testing
POM_DEVELOPER_ID=ackee
POM_DEVELOPER_NAME=Ackee
POM_DEVELOPER_EMAIL=info@ackee.cz
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_SCM_CONNECTION=scm:git:github.com/ackeecz/danger-kotlin-testing.git
POM_SCM_DEVELOPER_CONNECTION='scm:git:ssh://github.com/ackeecz/danger-kotlin-testing.git'
POM_SCM_URL=https://github.com/ackeeCZ/danger-kotlin-testing/tree/main

VERSION=1.0.2
ARTIFACT_ID=danger-kotlin-testing
POM_NAME=Danger Kotlin Testing
POM_YEAR=2021
POM_DESCRIPTION=Plugin for danger-kotlin processing of test results
