name: Publish

on:
  push:
    tags:
      - 'v*'

env:
  GPG_KEY: ${{ secrets.ANDROID_GPG_KEY }}
  GPG_PASSWORD: ${{ secrets.ANDROID_SIGNING_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.ANDROID_MAVEN_CENTRAL_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.ANDROID_MAVEN_CENTRAL_PASSWORD }}

jobs:
  build:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      # actions/checkout can't be included in the composite setup action, because the composite
      # action needs to be first checked out by the checkout action.
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Preflight checks
        uses: ./.github/actions/preflight-check

      - name: Publish to Maven Central
        run: |
          ./gradlew --stacktrace publishAndReleaseToMavenCentral \
            -PsigningInMemoryKey=$GPG_KEY \
            -PsigningInMemoryKeyPassword=$GPG_PASSWORD \
            -PmavenCentralUsername=$MAVEN_USERNAME \
            -PmavenCentralPassword=$MAVEN_PASSWORD
